### ISSUE TITLE
ID cloud automate logging secret installation

### ISSUE THREAD

**Issue by adam-cyclones** [rockcarver/frodo#105]
**Is your feature request related to a problem? Please describe.**
It is possible to use puppeteer to login and go generate a new logging secret, it could then grab that and provide it back to a node.js script, I think this would mean the command could become:

frodo logs install openam-fr-example.forgeblocks.com amadmin SuperSecretPassword

You could then use this command without ever logging into or using the UI to set up logging!

**Describe alternatives you've considered**
Not doing it

**Comment by atomicsamurai** [comment]
In my opinion, this makes good sense. frodo itself can generate the keys as part of the different `logs` subcommands (if not found in saved connection details).
