### ISSUE TITLE
Restructure admin command

### ISSUE THREAD

**Issue by vscheuber** [rockcarver/frodo#133]
Restructure command to use executable (sub)commands in commander

**Comment by adam-cyclones** [comment]
Based on https://github.com/rockcarver/frodo/issues/132 replicate here:

Admin
📦admin
┗ 📜cmd.js

Becomes:
📦admin
┣ 📜admin-add-autoid-static-user-mapping.js
┣ 📜admin-create-oauth2-client-with-admin-privileges.js
┣ 📜admin-get-access-token.js
┣ 📜admin-grant-oauth2-client-admin-privileges.js
┣ 📜admin-hide-generic-extension-attributes.js
┣ 📜admin-list-oauth2-clients-with-admin-privileges.js
┣ 📜admin-list-oauth2-clients-with-custom-privileges.js
┣ 📜admin-list-static-user-mappings.js
┣ 📜admin-remove-static-user-mapping.js
┣ 📜admin-repair-org-model.js
┣ 📜admin-revoke-oauth2-client-admin-privileges.js
┣ 📜admin-show-generic-extension-attributes.js
┗ 📜admin.js

Helping out
Quickly create all needed files:

touch admin-add-autoid-static-user-mapping.js admin-list-static-user-mappings.js admin-create-oauth2-client-with-admin-privileges.js admin-remove-static-user-mapping.js admin-get-access-token.js admin-repair-org-model.js admin-grant-oauth2-client-admin-privileges.js admin-revoke-oauth2-client-admin-privileges.js admin-hide-generic-extension-attributes.js admin-show-generic-extension-attributes.js admin-list-oauth2-clients-with-admin-privileges.js admin.js admin-list-oauth2-clients-with-custom-privileges.js
