### ISSUE TITLE
application export should have -k like script export and journey export

### ISSUE THREAD

**Issue by jgdtech** [rockcarver/frodo#361]
**Is your feature request related to a problem? Please describe.**
frodo application export does not have -k (--insecure) so it won't work behind our corporate SSL Interceptor.

**Describe the solution you'd like**
Add -k option like "script export" and "journey export" have

**Describe alternatives you've considered**
No other alternatives

**Additional context**
No additional context

**Comment by vscheuber** [comment]
Duplicate of #280 and was fixed in 0.7.0 back in July.

Can you please check which version of Frodo you are running and possibly update to the latest version?

**Comment by jgdtech** [comment]
frodo -v shows 0.6.1 [v16.14.2]

How do I get up to v7?

**Comment by vscheuber** [comment]
Easiest is to just go to the [Release Page](https://github.com/rockcarver/frodo/releases) and download the latest version.
